version: "3.4"

services:
  app:
    image: shorturl
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3005:3005
  short-mongo-db:
    image: mongo
    ports:
      - "27017:27017"
